environment:
  matrix:
    - nodejs_version: "6"

# Install scripts. (runs after repo cloning)
install:
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run e2e

# Don't actually build.
build: off